### CREATE PRODUCT
POST http://localhost:5000/product
X-Api-Version: 1.0
Content-Type: application/json

{
  "id": "7871bc38-4ca1-4fea-bdd5-49d8a3d93afd",
  "title": "Samsung TV 55",
  "description": "Perfect for movies",
  "price": 70000,
  "status": "closed"
}