### CREATE PRODUCT
POST http://localhost:5000/product
X-Api-Version: 1.0
Content-Type: application/json

{
  "id": "8a5b3e4a-3e08-492c-869e-317a4d04616a",
  "title": "Samsung TV 55",
  "description": "Perfect for movies",
  "price": 70000,
  "status": 0
}